name: Compile Resume

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 1.0)"
        required: true
        default: "1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_xelatex: false

      - name: Get version number
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            # Extract version from git tag if available, otherwise use 1.0
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0")
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Rename PDF with version
        run: |
          mkdir -p releases
          cp resume.pdf "releases/puneet_ludu_v${{ env.VERSION }}.pdf"
          # Also copy to root for direct access
          cp resume.pdf "puneet_ludu_resume.pdf"

      - name: Move current README to RUNSTEPS.md
        run: |
          if [ -f README.md ]; then
            cp README.md RUNSTEPS.md
          fi

      - name: Create new README.md with iframe
        run: |
          # Extract basic information from LaTeX file
          NAME=$(grep -oP '\\textbf{\\color{namecolor}Puneet Ludu}' resume.tex | sed 's/\\textbf{\\color{namecolor}//g' | sed 's/}//g')

          # Create README content with iframe
          cat > README.md << EOF
          # $NAME's Resume

          ## Latest Version: v${{ env.VERSION }}

          <iframe src="puneet_ludu_resume.pdf" width="100%" height="800px" style="border: none;"></iframe>

          ## Download Options

          - [Download PDF](puneet_ludu_resume.pdf)
          - [View on GitHub](https://github.com/puneetsl/resume/blob/main/puneet_ludu_resume.pdf)

          ## Compilation Instructions

          For instructions on how to compile this resume, see [RUNSTEPS.md](RUNSTEPS.md).
          EOF

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: releases/puneet_ludu_v${{ env.VERSION }}.pdf
          retention-days: 30

      - name: Upload README artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-readme
          path: README.md
          retention-days: 30

      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/puneet_ludu_v${{ env.VERSION }}.pdf
            README.md
          tag_name: v${{ env.VERSION }}
          name: Resume v${{ env.VERSION }}
          body: |
            Resume version ${{ env.VERSION }}

            Automatically compiled from the LaTeX source.
          draft: false
          prerelease: false

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md RUNSTEPS.md puneet_ludu_resume.pdf
          git commit -m "Update README and PDF for version ${{ env.VERSION }}" || echo "No changes to commit"
          git push
